spring.application.name=leave
spring.datasource.url=jdbc:mysql://localhost:3306/leavedb
spring.datasource.username=root
spring.datasource.password=selvan

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true